### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by sethoscope** [sethoscope/heatmap#41]
Test coverage dropped significantly.
https://coveralls.io/builds/10860249

**Comment by hugovk** [comment]
Strange thing is I can't even see the builds at [Travis CI](https://travis-ci.org/sethoscope/heatmap/):

![image](https://user-images.githubusercontent.com/1324225/30294699-a8736d78-9746-11e7-8d69-058e08975414.png)

**Comment by hugovk** [comment]
Some things to check:

* [ ] Make sure Travis CI and Coveralls are enabled for this repo, so that they run for every PR, and we can check the coverage changes and make sure it's kept at a reasonable level before merge. This also gives a chronological log of all pushes (PR or direct) showing when dependencies change.

* [ ] It looks like the main difference is from the way the Coverage command works, something has changed between 4.0.3 and 4.3.4 which causes how we use it to not collect the same coverage. For example, test_system.py is now collecting no coverage: March 2016 https://travis-ci.org/hugovk/heatmap/jobs/117235776#L271  April 2017: https://travis-ci.org/hugovk/heatmap/jobs/225354088#L266

**Comment by sethoscope** [comment]
I'm not sure why Travis lost track of it. I logged in there and reauthorized them, and now it's back.
